// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const supabaseUrl = "https://hipoantgjdtzsgtkohxa.supabase.co";
const supabaseKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhpcG9hbnRnamR0enNndGtvaHhhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MjY3ODkzOTcsImV4cCI6MjA0MjM2NTM5N30.m8ttSOFg0gOmA2GnxsuRsEGGp5bpRHoqvRVbQx7QCWY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(supabaseUrl, supabaseKey);